### ISSUE TITLE
Roles and Responsibilities add-on

### ISSUE THREAD

**Issue by ThatGuyLLC** [input-output-hk/cardano-engineering-handbook#47]
HI Michael, 
Reading through the handbook and having some discussion with Marcin, would it be good to establish the core list of maintainers via the readme or the *cabal files, this may also be specific to what files are included to the repo. Although it is a recommendation, I do see utility identifying the list to ensure transparency of who is the Point of Contact for reviewing, maintaining, etc. 
We are encouraging this as a facet for the MBO to adopt but didn't not specify how to capture the item. What are your thoughts, really do appreciate your insights?

**Comment by michaelpj** [comment]
I'm not quite sure what you're asking for? There's already something about this [here](https://input-output-hk.github.io/cardano-engineering-handbook/policy/project/index.html#roles-and-responsibilities), was there something specific you wanted to add to that?

**Comment by michaelpj** [comment]
I didn't want to be too prescriptive since I don't think we should assume too much uniformity in our team structure. I'm already worried that trying to identify specific maintainers/backup maintainers may be too prescriptive. Or that we should clarify what that means.

**Comment by michaelpj** [comment]
If you want to talk about `.cabal` files specifically, see https://github.com/input-output-hk/cardano-engineering-handbook/issues/12

**Comment by coot** [comment]
I think we can close this issue.
