### ISSUE TITLE
Reference some public Haskell style guides?

### ISSUE THREAD

**Issue by effectfully** [input-output-hk/cardano-engineering-handbook#54]
The Coding style sections says

> There aren't many examples of public Haskell style guides

but there are in fact plenty!

- this famous [one](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md) by Johann Tibell
- this [one](https://kowainik.github.io/posts/2019-02-06-style-guide) by Kowainik
- this [one](https://enso.org/docs/developer/enso/style-guide/haskell.html) by Enso
- this [one](http://courses.cms.caltech.edu/cs11/material/haskell/misc/haskell_style_guide.html) by CMS
- this [one](https://comp.anu.edu.au/courses/comp1100/resources/04-style) by Australian National University
- this [one](https://memo.barrucadu.co.uk/haskell-style-guide.html)
- this [one](http://urchin.earth.li/~ian/style/haskell.html)
- I'm sure there are more

I'm not sure if we should endorse any of these, but the statement that there aren't many examples of Haskell guides seems wrong.

**Comment by michaelpj** [comment]
I wasn't aware of any! But yes, we can reference some.
